### ISSUE TITLE
EMQX Operator does not remove old StatefulSet + new pods do not auto-join cluster

### ISSUE THREAD

**Issue by demaro07** [emqx/emqx-operator#1130]
# Environment

- **Kubernetes:** AKS v1.30.5  
- **EMQX Operator Version:** 2.2.29-beta.1  
- **EMQX Version:** 5.8.6 (Open Source)  
- **EMQX API Version:** apps.emqx.io/v2beta1  
- **Cluster Discovery:** discovery_strategy = dns (default)

# Problem 1: Old StatefulSet remains after Recreate

When updating the EMQX CR (e.g., changing the `image` or `imagePullSecrets`), the operator correctly creates a new StatefulSet.

Example:

```yaml
status:
  coreNodesStatus:
    currentRevision: emqx-core-6c78667db5
    updateRevision: emqx-core-cfdbb956b
```

However:

- The old StatefulSet is **not removed**, even though `updateStrategy.type: Recreate` is set.
- The new set does not become the `currentRevision`, even when all pods are ready.
- Logs only show:
  ```
  got different pod template for EMQX core nodes, will create new statefulSet
  ```
  but there is no indication of switching or deletion.

# Problem 2: New pods do not auto-join cluster (dns discovery)

After an update, new EMQX pods often **do not automatically join** the existing cluster, even though `discovery_strategy = dns` is in use.

- The `emqx-headless` headless service is correctly configured.
- Pods start with hostnames like `emqx-core-0.emqx-headless.emqx-broker.svc.cluster.local`
- Still, `emqx_ctl cluster status` shows each pod as an isolated cluster.

Only manual joining works:

```bash
emqx_ctl cluster join emqx@emqx-core-0.emqx-headless.emqx-broker.svc.cluster.local
```

# Expected Behavior

- The old StatefulSet should be removed automatically during Recreate when the new one is ready.
- New pods should auto-join the cluster using DNS discovery.

# Related Issues / Discussion
- [Deploy emqx on k8s，the condition of pods show ReadinessGatesNotReady ](https://github.com/emqx/emqx-operator/discussions/1126)
- [Nodes cannot join into cluster automatically using emqx-operator in k8s](https://github.com/emqx/emqx/issues/12630)

**Comment by Rory-Z** [comment]
Hi @demaro07 I think this is one problem, because if new EMQX pod didn't join EMQX cluster, then emqx operator will think they are not ready yet.
Could you please doing those follow steps to check network envrionment
1. Doing `kubectl exec -it ` to the new EMQX pod, and running `echo $EMQX_CLUSTER__DNS__NAME`
2. Create a new pod which image is `curlimages/curl` or other image that you want, and running `nslookup -type=srv emqx-headless.default.svc.cluster.local`, the headless server address is form the echo command in step 1.
3. Share the nslookup command output in this issue.

**Comment by demaro07** [comment]
Hi @Rory-Z,

Thanks a lot for the quick support! 🙏  

I followed your suggested steps and did some testing. Here are the results along with screenshots:

---

## ✅ Step 1 & 2 – EMQX Environment Variables

I ran the following commands in the new EMQX pod:

```bash
echo $EMQX_CLUSTER__DNS__RECORD_TYPE
```
✔️ Output: `srv`

```bash
echo $EMQX_CLUSTER__DNS__NAME
```
✔️ Output: `emqx-headless.emqx-broker.svc.cluster.local`

📸 Screenshot attached

![Image](https://github.com/user-attachments/assets/bf16d099-cce2-49c0-90aa-5fd7a864d219)

---

## ✅ Step 3 – `nslookup` from Another Pod

I used a test pod and ran:

```bash
nslookup -type=SRV emqx-headless.emqx-broker.svc.cluster.local
```

⛔ **Result**: I'm getting a **timeout**.

```text
Connection to 172.16.0.10#53 failed: timed out.
no servers could be reached
```

📸 Screenshot attached

![Image](https://github.com/user-attachments/assets/6f0bb38e-8b77-44bc-9d4d-85bca7ee2546)

---

## 🔍 Additional Check – Regular `nslookup`

When I run a regular `nslookup` **without** `-type=SRV`, the domain resolves successfully and I get all the pod IPs behind the headless service.

📸 Screenshot attached

![Image](https://github.com/user-attachments/assets/2573ba0c-c43f-4ac9-bf6f-48fed3078eaa)

---

Let me know if there's anything else I can try — happy to debug further!

Thanks again 🙌

**Comment by Rory-Z** [comment]
Looks `SRV` record is not work in your K8s cluster. Could you please describe your K8s ? Is it running on some cloud provider server or running on your self machine ?

**Comment by demaro07** [comment]
Thanks for your reply, @Rory-Z!

Your hint about the SRV record not working led me to further investigate the DNS resolution issue. I eventually found that **TCP traffic on port 53 to CoreDNS** was being **blocked by Cilium network policies** in our Kubernetes cluster (running in Azure AKS). After adjusting the network policies to allow TCP/53 ingress to CoreDNS, **SRV resolution now works correctly**, and the EMQX cluster bootstraps without DNS errors.

---

## Follow-up Issues

However, I’m now observing two follow-up issues:

### 1. Old StatefulSet Not Deleted

The old StatefulSet is not deleted after a new one becomes active (blue-green style deployment).  
The Operator logs show the following error:

```
failed to scale down old statefulSet: StatefulSet.apps [...] Invalid value: -1: must be greater than or equal to 0
```

This looks like a bug that has already been addressed in [this commit](https://github.com/emqx/emqx-operator/commit/4383b83411ac360e871aeee385f842b7d60ba79e), but I am currently using version `emqx/emqx-operator-controller:2.2.29-beta.1`, which seems to be affected.

### 2. PVCs of Old StatefulSet Not Removed

The PVCs of the old StatefulSet remain and are not removed.

It’s unclear to me what the expected behavior is here:
- Should the old PVCs be deleted automatically when the StatefulSet is removed?
- Or should the PVCs be reused by the new StatefulSet?
- Or is manual cleanup expected?

---


Thanks again!

**Comment by Rory-Z** [comment]
About issue 1, it's strange, could you please show current EMQX Pod list ? Is there any old EMQX pod still exist ?

About issue 2, it's not a bug, we deliberate keep old PVCs and old StatefulSets (set replicas to 0) so if new StatefulSet has any problem then can be rollback. You can set `.spec.revisionHistoryLimit` change it, and also, you can delete them by manual.

**Comment by demaro07** [comment]
Thank you for the clarification regarding the PVCs and StatefulSet retention for rollback purposes – that makes perfect sense now.

## Regarding Issue 1:

There are no old EMQX pods running. Only the latest StatefulSet is active:

```
NAME                               READY   STATUS    RESTARTS   AGE
emqx-core-64bb8c4cf5-0             1/1     Running   0          11m
emqx-core-64bb8c4cf5-1             1/1     Running   0          11m
emqx-core-64bb8c4cf5-2             1/1     Running   0          11m
```

However, I’m still seeing this error in the operator logs:

```
failed to scale down old statefulSet: StatefulSet.apps "emqx-core-66c58b7644" is invalid: spec.replicas: Invalid value: -1: must be greater than or equal to 0
```

This appears to be a bug where the operator incorrectly sets replicas: -1 when trying to manage the old StatefulSet.


And additionally, I noticed that the EMQX Operator ServiceAccount cannot patch events due to missing RBAC permissions:

```
User "system:serviceaccount:emqx-operator-system:emqx-operator" cannot patch resource "events" in API group "" in the namespace "emqx-broker"
```

Should this RBAC permission be granted by default, or is this something I should adjust manually? Could it also relate to prior NetworkPolicy restrictions?

## Environment Details:

- **Kubernetes:** v1.30.5 on Azure AKS
- **EMQX Operator:** emqx/emqx-operator-controller:2.2.29-beta.1
- **EMQX Broker:** emqx:5.8.6 (apiVersion: apps.emqx.io/v2beta1)

Let me know if you need more details!

**Comment by Rory-Z** [comment]
Hi @demaro07 Cloud you please try 2.2.29-beta.2 https://github.com/emqx/emqx-operator/releases/tag/2.2.29-beta.2

**Comment by demaro07** [comment]
Hi @Rory-Z 

I just tested the new release 2.2.29-beta.2 — both issues are now resolved!

✅ The error regarding the StatefulSet scaling (replicas: -1) no longer appears.
✅ The RBAC permissions for event patching are correctly set, and no further errors are logged.

Thank you very much for the quick and professional support!
Really appreciate how fast you addressed and fixed the issues. Great job!

**Comment by Rory-Z** [comment]
Thanks @demaro07 EMQX operator 2.2.29 has been released: https://github.com/emqx/emqx-operator/releases/tag/2.2.29, it's totally base 2.2.29-beta.2
